# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build CI-CD

on:
  push:
  pull_request:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: "Setup Use Node.js"
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - name: "Setup Golang"
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Login to Docker Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | \
          docker login docker.pkg.github.com -u docker --password-stdin
      - name: "[FRONTEND] - Build"
        run: npm ci && npm run build --if-present
        working-directory: frontend
      - name: "[BACKEND]"
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  deploy:
    runs-on: ubuntu-latest
    needs: [release]
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Invoke workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: deploy
          repo: dohrm-gametools/deploy
          ref: master
          token: ${{ secrets.DISPATCH_SECRET }}
